### ISSUE TITLE
Using Adafruit RFM9x module

### ISSUE THREAD

**Issue by lukecyca** [manuelbl/ttn-esp32#1]
I'm using a regular ESP32 along with this RFM9x module.

https://learn.adafruit.com/adafruit-rfm69hcw-and-rfm96-rfm95-rfm98-lora-packet-padio-breakouts/pinouts#spi-logic-pins-2-6

I've hooked it up such that the pins are connected to the following pins on the module:

```
#define TTN_SPI_HOST      HSPI_HOST
#define TTN_SPI_DMA_CHAN  1
#define TTN_PIN_SPI_SCLK  [SCK]
#define TTN_PIN_SPI_MOSI  [MOSI]
#define TTN_PIN_SPI_MISO  [MISO]
#define TTN_PIN_NSS       [CS]
#define TTN_PIN_RXTX      TTN_NOT_CONNECTED
#define TTN_PIN_RST       [RST]
#define TTN_PIN_DIO0      [G0]
#define TTN_PIN_DIO1      [G1]
```

However, it fails at `radio.c:739`. I instrumented the code and found that the `RegVersion` returned is `0x9` (0b1001) instead of the expected `0x12` (0b10010). Given the similar-but-shifted binary representations, I suspect a timing/sync problem on the bus.

Any ideas?

**Comment by manuelbl** [comment]
I agree with your analysis: It seems to be SPI related and it's likely a timing issue and not a wiring issue (otherwise `0xff` would be returned).

I propose you experiment with the SPI parameters. In `hal_spi_init()` in `hal_esp32.c` you can make the following changes:

* Add the `cs_ena_posttrans` line (see below). It has helped in a previous project.
* Or change the `mode` to 1, 2 or 3

The relevant code is:

    spi_device_interface_config_t spi_device_intf_config = {
        .mode = 0,
        .clock_speed_hz = CONFIG_TTN_SPI_FREQ,
        .command_bits = 0,
        .address_bits = 8,
        .spics_io_num = lmic_pins.nss,
        .queue_size = SPI_QUEUE_SIZE,
        .cs_ena_posttrans = 2
    };

Do you happen to have a DSO? If so, try to capture the SPI communication and attach it to the issue. It would be very helpful.

**Comment by lukecyca** [comment]
Thanks - `mode = 1` worked!

**Comment by manuelbl** [comment]
It's a bit surprising that `mode = 1` works. The datasheet clearly specifies mode 0.

Today I've tested it with a RFM95W module (the green module on your Adafruit board) and did't have any problems with the unmodified software.

Most likely, the level converter / buffer chip on the Adafruit board change the timing. So I've ordered the Adafruit board and will test it myself. I'll try to find a setup that works with as many boards as possible.
